### ISSUE TITLE
Is there an ReadMe.md?

### ISSUE THREAD

**Issue by xiaozhu2007** [Darlatanujcodes10/Mini_Games#1]
Is there an HTML version?

**Comment by xiaozhu2007** [comment]
Is there a remdme.md?
This will let us know how to use it

**Comment by Darlatanujcodes10** [comment]
I have only saved it in php and I haven't used any server side scripting so you can use the same in html files.

**Comment by Darlatanujcodes10** [comment]
> Is there a remdme.md?
> This will let us know how to use it

Sorry....but I don't have a readme.md
But the index.php is the main menu file and the rest one,two,three,four are the game files.Each one for a different game

**Comment by Darlatanujcodes10** [comment]
> Is there an HTML version?

I have only saved it in php and I haven't used any server side scripting so you can use the same in html files.

**Comment by xiaozhu2007** [comment]
> > 有HTML版本吗？
> 
> 我只将其保存在php中，并且未使用任何服务器端脚本，因此您可以在html文件中使用相同的脚本。

OK，
